import random
import string

def gerar_senha(tamanho=12):
    caracteres = string.ascii_letters + string.digits
    senha = ''.join(random.choice(caracteres) for _ in range(tamanho))
    return senha



tecnologias = [
    "Cheddar",
    "Gouda",
    "Brie",
    "Parmesão",
    "Roquefort",
    "Mozzarella",
    "Gorgonzola",
    "Feta",
    "Camembert",
    "Provolone",
    "Emmental",
    "Queijo de cabra",
    "Queijo de ovelha",
    "Queijo de cabra",
    "Requeijão",
    "Ricota",
    "Cottage",
    "Queijo Azul",
    "Queijo Coalho",
    "Queijo Canastra",
    "Queijo Minas",
    "Queijo Serra da Estrela",
    "Queijo Gruyère",
    "Queijo Gouda",
    "Queijo Edam",
    "Queijo Gruyère",
    "Queijo Parmesão",
    "Queijo Gouda",
    "Queijo Boursin",
    "Queijo Feta",
    "Queijo Taleggio",
    "Queijo Stilton",
    "Queijo Roquefort",
    "Queijo Camembert",
    "Queijo de Cabra",
    "Queijo de Azeitão",
    "Queijo do Reino",
    "Queijo Prato",
    "Queijo Mussarela",
    "Queijo Gouda",
    "Queijo Coalho",
    "Queijo Canastra",
    "Queijo Minas",
    "Queijo Serra da Estrela",
    "Queijo Gruyère",
    "Queijo Gouda",
    "Queijo Edam",
    "Queijo Gruyère",
    "Queijo Parmesão",
    "Queijo Gouda",
    "Queijo Boursin",
    "Holandesa",
    "Jersey",
    "Guzerá",
    "Sindi",
    "Nelore",
    "Caracu",
    "Tabapuã",
    "Girolando",
    "Simental",
    "Brahman",
    "Bonsmara",
    "Senepol",
    "Angus",
    "Hereford",
    "Red Angus",
    "Santa Gertrudis",
    "Mestiça",
    "Pardo Suíço",
    "Gir Leiteiro",
    "Normando",
    "Pitangueiras",
    "Canchim",
    "Limousin",
    "Marchigiana",
    "Braford",
    "Simbrasil",
    "Charolesa",
    "Zebu",
    "Brangus",
    "Simental",
    "Brahman",
    "Bonsmara",
    "Senepol",
    "Angus",
    "Hereford",
    "Red Angus",
    "Santa Gertrudis",
    "Mestiça",
    "Pardo Suíço",
    "Gir Leiteiro",
    "Normando",
    "Pitangueiras",
    "Canchim",
    "Limousin",
    "Marchigiana",
    "Braford",
    "Simbrasil",
    "Charolesa",
    "Zebu"
]

nichos_de_fornecedores = [
    "Fornecedores de leite cru",
    "Fornecedores de leite pasteurizado",
    "Fornecedores de culturas lácticas",
    "Fornecedores de coalho",
    "Fornecedores de fermento",
    "Fornecedores de sal",
    "Fornecedores de prensas de queijo",
    "Fornecedores de formas de queijo",
    "Fornecedores de tanques de fermentação",
    "Fornecedores de equipamentos de resfriamento de leite",
    "Fornecedores de equipamentos de aquecimento de leite",
    "Fornecedores de equipamentos de pasteurização",
    "Fornecedores de máquinas de ordenha",
    "Fornecedores de tanques de armazenamento de leite",
    "Fornecedores de queijarias modulares",
    "Fornecedores de sistemas de controle de temperatura",
    "Fornecedores de sistemas de limpeza CIP (Cleaning-in-Place)",
    "Fornecedores de embalagens para queijo",
    "Fornecedores de etiquetas personalizadas",
    "Fornecedores de sistemas de rastreabilidade",
    "Fornecedores de equipamentos de corte e embalagem",
    "Fornecedores de máquinas de envase",
    "Fornecedores de sistemas de transporte interno",
    "Fornecedores de análise laboratorial de leite e queijo",
    "Fornecedores de sistemas de tratamento de água",
    "Fornecedores de aditivos alimentares",
    "Fornecedores de produtos de limpeza e sanitização",
    "Fornecedores de uniformes e equipamentos de proteção individual (EPIs)",
    "Fornecedores de consultoria em produção de queijo",
    "Fornecedores de treinamento em técnicas de fabricação de queijo",
    "Fornecedores de serviços de certificação e qualidade",
    "Fornecedores de sistemas de gestão de produção",
    "Fornecedores de sistemas de gestão de estoque",
    "Fornecedores de sistemas de gestão de vendas",
    "Fornecedores de sistemas de gestão financeira",
    "Fornecedores de soluções de embalagem sustentável",
    "Fornecedores de energia renovável",
    "Fornecedores de seguro para indústria de laticínios",
    "Fornecedores de transporte refrigerado",
    "Fornecedores de logística de distribuição",
    "Fornecedores de tecnologia de embalagem a vácuo",
    "Fornecedores de equipamentos de transporte de queijo",
    "Fornecedores de equipamentos de inspeção de qualidade",
    "Fornecedores de equipamentos de análise de textura",
    "Fornecedores de equipamentos de análise de umidade",
    "Fornecedores de sistemas de purificação de ar",
    "Fornecedores de sistemas de controle de umidade",
    "Fornecedores de sistemas de tratamento de efluentes",
    "Fornecedores de tecnologia de resfriamento rápido",
    "Fornecedores de sistemas de embalagem a vácuo"
]
print(nichos_de_fornecedores[49])
